FROM python:3.6

RUN apt update && apt install supervisor -y
RUN pip install --upgrade pip

WORKDIR /app
ADD requirements.txt .

RUN pip install -r requirements.txt --upgrade
ADD resetapp/etc /etc

CMD ["/usr/bin/supervisord", "--configuration=/etc/supervisor/supervisord.conf"]
